# Generated by Django 3.1.7 on 2021-03-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Enter Firts name', max_length=50, verbose_name='fname')),
                ('lname', models.CharField(help_text='Enter Last name', max_length=50, verbose_name='lname')),
            ],
            options={
                'ordering': ['fname'],
                'unique_together': {('fname', 'lname')},
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, help_text='Enter City', max_length=50, verbose_name='City')),
                ('address', models.CharField(blank=True, help_text='Enter address', max_length=150, verbose_name='address')),
                ('phone', models.CharField(help_text='Phone number', max_length=9, verbose_name='Phone')),
                ('contactUrl', models.CharField(blank=True, help_text='Enter valid web adsress', max_length=250, null=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb.contact')),
            ],
        ),
    ]
