# Generated by Django 3.1.7 on 2021-03-19 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, help_text='Enter address', max_length=150, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, help_text='Enter City', max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contactUrl',
            field=models.CharField(blank=True, help_text='Enter valid web adsress', max_length=250, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, upload_to='pb/static/images'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, help_text='Phone number', max_length=9, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
